config/routes.rb
Rails.application.routes.draw do
  resources :driversandcars do
    resources :getdrivercar
  end
  resources :drivers
  resources :cars
  root "articles#index"
  # get 'driversandcars/getdrivercar' to: "driversandcars#getdrivercar"

  resources :articles
end

app/models/driversandcar.rb
class Driversandcar < ApplicationRecord
    belongs_to :car
    belongs_to :driver
end

app/controllers/driversandcars_controller.rb
class DriversandcarsController < ApplicationController
  before_action :set_driversandcar, only: %i[ edit update destroy ]

  # GET /driversandcars or /driversandcars.json
  def index
    @driversandcars = Driversandcar.all
  end

  # GET /driversandcars/1 or /driversandcars/1.json
  def show
    
  end

  # GET /driversandcars/new
  def new
    @driversandcar = Driversandcar.new
  end

  # GET /driversandcars/1/edit
  def edit
    @driversandcar = Driversandcar.find(params[:id])
    
  end

  def getdrivercar
    if params[:driver_id].in? [nil,0]
      @driversandcar = Driversandcar.select('driversandcar.created_at','cars.title','driversandcar.car_id')
        .joins(:cars)
        .where(['driversandcar.driver_id =?', params[:driver_id]])
      render json: { status: 'SUCCSES', message: "load cars of driver", data: @driversandcar}, status: :ok
    else
      if params[:car_id].in? [nil,0]
        @driversandcar = Driversandcar.select('driversandcar.created_at','drivers.name','driversandcar.driver_id')
        .joins(:drivers)
        .where(['driversandcar.car_id =?', params[:car_id]])
       render json: { status: 'SUCCSES', message: "load drivers of car", data: @driversandcar}, status: :ok
      end
    end
  end

  # POST /driversandcars or /driversandcars.json
  def create
    @driversandcar = Driversandcar.new(driversandcar_params)

    respond_to do |format|
      if @driversandcar.save
        format.html { redirect_to @driversandcar, notice: "Driversandcar was successfully created." }
        format.json { render :index, status: :created, location: @driversandcar }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @driversandcar.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /driversandcars/1 or /driversandcars/1.json
  def update
    @driversandcar = Driversandcar.find(params[:id])
    respond_to do |format|
      if @driversandcar.update(driversandcar_params)
        format.html { redirect_to @driversandcar, notice: "Driversandcar was successfully updated." }
        format.json { render :index, status: :ok, location: @driversandcar }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @driversandcar.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /driversandcars/1 or /driversandcars/1.json
  def destroy
    @driversandcar.destroy
    respond_to do |format|
      format.html { redirect_to driversandcars_url, notice: "Driversandcar was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_driversandcar
      # if params[:id] != '0'
      # @driversandcar = Driversandcar.find(params[:id])
      # else
      #   if params[:driver_id].in? [nil,0]
      #     @driversandcar = Driversandcar.select('driversandcar.created_at','cars.title','driversandcar.car_id')
      #       .joins( :cars)
      #       .where('driversandcar.driver_id =?', params[:driver_id])
      #   else
      #     if params[:car_id].in? [nil,0]
      #       @driversandcar = Driversandcar.select('driversandcar.created_at','drivers.name','driversandcar.driver_id')
      #      .joins(:drivers)
      #      .where('driversandcar.car_id =?', params[:car_id])
      #     end
      #   end
      # end
    end

    # Only allow a list of trusted parameters through.
    def driversandcar_params
      params.require(:driversandcar).permit(:car_id, :driver_id)
    end

    # def get_driver_car_params
    #   params.require(:driversandcar).permit(:driver_id)
    # end
    
    # def get_car_driver_params
    #   params.require(:driversandcar).permit(:car_id)
    # end
end

app/helpers/driversandcars_helper.rb
module DriversandcarsHelper
end

app/views/driversandcars/_form.html.erb
<%= form_with(model: driversandcar) do |form| %>
  <% if driversandcar.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(driversandcar.errors.count, "error") %> prohibited this driversandcar from being saved:</h2>

      <ul>
        <% driversandcar.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
  
    <%= form.label :driver_id %>
    <%# <%= form.number_field :driver_id %>
    <%= form.select(:driver_id, Driver.all.collect {|u| [u.name, u.id]}, :prompt => 'Select') %>
  </div>

    <div class="field">
    <%= form.label :car_id %>
    <%= form.select(:car_id, Car.all.collect {|u| [u.title, u.id]}, :prompt => 'Select') %>
  </div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/driversandcars/edit.html.erb
<h1>Editing Driversandcar</h1>

<%= render 'form', driversandcar: @driversandcar %>

<%= link_to 'Show', @driversandcar %> |
<%= link_to 'Back', driversandcars_path %>

app/views/driversandcars/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Select driver or car</h1>
 <%= form_with url: "/driversandcars/0/getdrivercar", method: :get do |form| %>
 <div class="field">
   <%= form.label :driver_id %>
   <%= form.select(:driver_id, Driver.all.collect {|u| [u.name, u.id]}, :prompt => 'Select') %>
  </div>

  <div class="field">
    <%= form.label :car_id %>
    <%= form.select(:car_id, Car.all.collect {|u| [u.title, u.id]}, :prompt => 'Select') %>
  </div>
 <%= form.submit "Submit" %>
<% end %>


<br>

app/views/driversandcars/new.html.erb
<h1>New Driversandcar</h1>

<%= render 'form', driversandcar: @driversandcar %>

<%= link_to 'Back', driversandcars_path %>

app/views/driversandcars/show.html.erb
<p id="notice"><%= notice %></p>

<%# <%= link_to 'Edit', edit_driversandcar_path(@driversandcar) %> 
<%= link_to 'Get driver car', driversandcars_path %>
<br>
<%= link_to 'New Car', new_car_path %>

<br>
<%= link_to 'New Driver', new_driver_path %>
<br>
<%= link_to 'New Driversandcar', new_driversandcar_path %>